name: Build README
on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 */2 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repo
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
        architecture: x64
    - name: Install dependencies
      run: python -m pip install -r requirements.txt
    - name: Update README
      run: |-
        python build.py
        cat README.md
    - name: Commit and push if changed
      run: |-
        git diff
        git config --global user.email "taruninsa1@gmail.com"
        git config --global user.name "Tarun Singh"
        git add -A
        git commit -m "Updated readme" || exit 0
        git push
